version: 0.2

phases:
  install:
    commands:
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - pnpm run build  # Builds the project
      - aws cloudfront create-invalidation --distribution-id E1J0UER6Y04W2A --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: out  # Directory with output files (e.g., React app)